service: testing
app: testing-1
org: ingmjgq7

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    event: 
      - http:
        path: integrate
        method: post